name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: write
  pages: write

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npx jest --coverage --runInBand
        env:
          CI: true

      - name: Show coverage summary (for logs)
        run: |
          echo "=== coverage/coverage-summary.json ==="
          if [ -f coverage/coverage-summary.json ]; then
            cat coverage/coverage-summary.json
          else
            echo "No coverage summary found"
          fi

      - name: Upload coverage to Codecov (tokened)
        if: env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          flags: unit
          fail_ci_if_error: true
          token: ${{ env.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov (tokenless via GitHub App)
        if: env.CODECOV_TOKEN == ''
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          flags: unit
          fail_ci_if_error: false

      - name: Upload coverage artifact (fallback)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  e2e-tests:
    name: E2E tests (Playwright)
    runs-on: ubuntu-latest
    needs: unit-tests
    env:
      PLAYWRIGHT_BASE_URL: http://127.0.0.1:5500
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests (start http-server + run Playwright)
        run: |
          mkdir -p test-results
          # Start a static server (background)
          npx http-server ./ -p 5500 -s > server.log 2>&1 &
          server_pid=$!
          echo "Server started with PID $server_pid"
          sleep 2

          # Run Playwright with both JSON and HTML reporters.
          # JSON reporter prints to stdout; we redirect that stdout into test-results/results.json
          # HTML reporter will produce playwright-report/ directory.
          npx playwright test --reporter=json --reporter=html > test-results/results.json
          exit_code=$?

          # Collect any axe JSON outputs produced by a11y tests (they should write into test-results/)
          echo "Listing test-results after Playwright run:"
          ls -la test-results || true
          echo "Listing playwright-report directory (if any):"
          ls -la playwright-report || true

          # Stop server
          kill $server_pid || true
          wait $server_pid 2>/dev/null || true

          exit $exit_code

      - name: "Debug: list test-results"
        run: |
          echo "PWD: $(pwd)"
          ls -la
          ls -la test-results || true
          if [ -f test-results/results.json ]; then
            echo "results.json exists"
            head -c 200 test-results/results.json | cat
          else
            echo "results.json NOT FOUND"
          fi

      - name: Upload Playwright results artifact (JSON)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/results.json
          retention-days: 7

      - name: Upload axe / accessibility artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: axe-results
          path: test-results/*.json
          retention-days: 7

      - name: "Upload Playwright artifacts (report directory: screenshots/videos)"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  lighthouse:
    name: Lighthouse audit + publish badges
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.14.x

      - name: Run LHCI (start server + LHCI)
        run: |
          npx start-server-and-test "npx http-server ./ -p 5500 -s" http://127.0.0.1:5500 "lhci autorun --config=lighthouserc.cjs"

      - name: "Debug: list .lighthouseci"
        run: |
          echo "PWD: $(pwd)"
          ls -la
          ls -la .lighthouseci || true
          if [ -f .lighthouseci/assertion-results.json ]; then
            echo "assertion-results.json exists"
            head -c 200 .lighthouseci/assertion-results.json | cat
          else
            echo ".lighthouseci/assertion-results.json NOT FOUND"
          fi

      - name: Download Playwright results artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-results
          path: ./test-results

      - name: "Debug: workspace before badge scripts"
        run: |
          echo "PWD: $(pwd)"
          echo "List root files:"
          ls -la
          echo "List .lighthouseci:"
          ls -la .lighthouseci || true
          echo "List test-results:"
          ls -la test-results || true
          if [ -f .lighthouseci/assertion-results.json ]; then
            echo ".lighthouseci/assertion-results.json exists (first 200 chars):"
            head -c 200 .lighthouseci/assertion-results.json || true
          fi
          if [ -f test-results/results.json ]; then
            echo "test-results/results.json exists (first 200 chars):"
            head -c 200 test-results/results.json || true
          fi

      - name: Extract LHCI scores -> badge JSON
        run: node scripts/lhci-to-badges.cjs

      - name: Extract Playwright results -> badge JSON
        run: node scripts/playwright-to-badge.cjs

      - name: "Debug: show public_badges contents"
        run: |
          echo "public_badges exists?"; ls -la public_badges || true
          echo "Show up to first 200 chars of each JSON:"
          for f in public_badges/*.json; do
            echo "---- $f ----"
            head -c 200 "$f" || true
            echo
          done

      - name: Publish badges to gh-pages
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public_badges
          publish_branch: gh-pages

      - name: Verify published Lighthouse badge (quick check)
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        run: |
          echo "Waiting a few seconds for Pages to update..."
          sleep 15
          curl -I "https://joshl26.github.io/lucha-tacos/lighthouse-accessibility.json" || true

      - name: Upload Lighthouse reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: .lighthouseci/
          retention-days: 7

      - name: Show Lighthouse summary
        run: node scripts/lighthouse-summary.cjs || echo "No summary script found"
